/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Frame;

/**
 *
 * @author ME1
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public AdminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        StudentPanel = new javax.swing.JPanel();
        TeacherPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CoursePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NoticePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NoticeLabel = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        CoursesTable2 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        NoticesTable = new javax.swing.JTable();
        CoursesTeacherLabel2 = new javax.swing.JLabel();
        NoticesLabel = new javax.swing.JLabel();
        exitLabel2 = new javax.swing.JLabel();
        CourseLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        CoursesTable1 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        CloursesTable = new javax.swing.JTable();
        assignCourseLabel = new javax.swing.JLabel();
        CoursesLabel = new javax.swing.JLabel();
        exitLabel3 = new javax.swing.JLabel();
        TeacherLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CoursesTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        TeachersTable = new javax.swing.JTable();
        CoursesTeacherLabel = new javax.swing.JLabel();
        TeachersLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        StudentLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        courseStudentLabel = new javax.swing.JLabel();
        StudentsLabel = new javax.swing.JLabel();
        exitLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ServicePanel = new javax.swing.JPanel();
        NoticeLink = new javax.swing.JLabel();
        ServiceLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentLink = new javax.swing.JLabel();
        TeacherLink = new javax.swing.JLabel();
        CourseLink = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentPanel.setBackground(new java.awt.Color(0, 0, 0));
        StudentPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        StudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TeacherPanel.setBackground(new java.awt.Color(0, 0, 0));
        TeacherPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        TeacherPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TeacherPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        CoursePanel.setBackground(new java.awt.Color(0, 0, 0));
        CoursePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        CoursePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CoursePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        NoticePanel.setBackground(new java.awt.Color(0, 0, 0));
        NoticePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        NoticePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        NoticePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        NoticePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        NoticeLabel.setBackground(new java.awt.Color(0, 0, 0));
        NoticeLabel.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        NoticeLabel.setForeground(new java.awt.Color(255, 255, 255));
        NoticeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoticeLabel.setText("Notice Management");
        NoticePanel.add(NoticeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jScrollPane8.setBackground(new java.awt.Color(0, 0, 0));

        CoursesTable2.setBackground(new java.awt.Color(0, 0, 0));
        CoursesTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Description", "Time Period"
            }
        ));
        jScrollPane8.setViewportView(CoursesTable2);

        NoticePanel.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 340, 390));

        jScrollPane9.setBackground(new java.awt.Color(0, 0, 0));

        NoticesTable.setBackground(new java.awt.Color(0, 0, 0));
        NoticesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Specialty"
            }
        ));
        jScrollPane9.setViewportView(NoticesTable);
        if (NoticesTable.getColumnModel().getColumnCount() > 0) {
            NoticesTable.getColumnModel().getColumn(3).setHeaderValue("Specialty");
        }

        NoticePanel.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 390));

        CoursesTeacherLabel2.setBackground(new java.awt.Color(0, 0, 0));
        CoursesTeacherLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CoursesTeacherLabel2.setForeground(new java.awt.Color(255, 255, 255));
        CoursesTeacherLabel2.setText("Courses Of Teachers");
        NoticePanel.add(CoursesTeacherLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 150, 20));

        NoticesLabel.setBackground(new java.awt.Color(0, 0, 0));
        NoticesLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NoticesLabel.setForeground(new java.awt.Color(255, 255, 255));
        NoticesLabel.setText("Notice");
        NoticePanel.add(NoticesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 20));

        exitLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel2.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel2.setText("X");
        exitLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel2MouseClicked(evt);
            }
        });
        NoticePanel.add(exitLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 29));

        CoursePanel.add(NoticePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        CourseLabel.setBackground(new java.awt.Color(0, 0, 0));
        CourseLabel.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        CourseLabel.setForeground(new java.awt.Color(255, 255, 255));
        CourseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CourseLabel.setText("Course Management");
        CoursePanel.add(CourseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jScrollPane6.setBackground(new java.awt.Color(0, 0, 0));

        CoursesTable1.setBackground(new java.awt.Color(0, 0, 0));
        CoursesTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Description", "Time Period"
            }
        ));
        jScrollPane6.setViewportView(CoursesTable1);

        CoursePanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 340, 390));

        jScrollPane7.setBackground(new java.awt.Color(0, 0, 0));

        CloursesTable.setBackground(new java.awt.Color(0, 0, 0));
        CloursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Specialty"
            }
        ));
        jScrollPane7.setViewportView(CloursesTable);
        if (CloursesTable.getColumnModel().getColumnCount() > 0) {
            CloursesTable.getColumnModel().getColumn(3).setHeaderValue("Specialty");
        }

        CoursePanel.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 390));

        assignCourseLabel.setBackground(new java.awt.Color(0, 0, 0));
        assignCourseLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        assignCourseLabel.setForeground(new java.awt.Color(255, 255, 255));
        assignCourseLabel.setText("Assignments Of Course");
        CoursePanel.add(assignCourseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 150, 20));

        CoursesLabel.setBackground(new java.awt.Color(0, 0, 0));
        CoursesLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CoursesLabel.setForeground(new java.awt.Color(255, 255, 255));
        CoursesLabel.setText("Courses");
        CoursePanel.add(CoursesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 20));

        exitLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel3.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel3.setText("X");
        exitLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel3MouseClicked(evt);
            }
        });
        CoursePanel.add(exitLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 29));

        TeacherPanel.add(CoursePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        TeacherLabel.setBackground(new java.awt.Color(0, 0, 0));
        TeacherLabel.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        TeacherLabel.setForeground(new java.awt.Color(255, 255, 255));
        TeacherLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TeacherLabel.setText("Teacher Management");
        TeacherPanel.add(TeacherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jScrollPane4.setBackground(new java.awt.Color(0, 0, 0));

        CoursesTable.setBackground(new java.awt.Color(0, 0, 0));
        CoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Description", "Time Period"
            }
        ));
        jScrollPane4.setViewportView(CoursesTable);

        TeacherPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 340, 390));

        jScrollPane5.setBackground(new java.awt.Color(0, 0, 0));

        TeachersTable.setBackground(new java.awt.Color(0, 0, 0));
        TeachersTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        TeachersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Specialty"
            }
        ));
        jScrollPane5.setViewportView(TeachersTable);
        if (TeachersTable.getColumnModel().getColumnCount() > 0) {
            TeachersTable.getColumnModel().getColumn(3).setHeaderValue("Specialty");
        }

        TeacherPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 390));

        CoursesTeacherLabel.setBackground(new java.awt.Color(0, 0, 0));
        CoursesTeacherLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CoursesTeacherLabel.setForeground(new java.awt.Color(255, 255, 255));
        CoursesTeacherLabel.setText("Courses Of Teachers");
        TeacherPanel.add(CoursesTeacherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 150, 20));

        TeachersLabel.setBackground(new java.awt.Color(0, 0, 0));
        TeachersLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TeachersLabel.setForeground(new java.awt.Color(255, 255, 255));
        TeachersLabel.setText("Teachers");
        TeacherPanel.add(TeachersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 20));

        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        TeacherPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 29));

        StudentPanel.add(TeacherPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        studentsTable.setBackground(new java.awt.Color(0, 0, 0));
        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email"
            }
        ));
        jScrollPane1.setViewportView(studentsTable);

        StudentPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 390));

        StudentLabel.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        StudentLabel.setForeground(new java.awt.Color(255, 255, 255));
        StudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentLabel.setText("Student Management");
        StudentPanel.add(StudentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 420, 41));

        coursesTable.setBackground(new java.awt.Color(0, 0, 0));
        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Description", "Time Period"
            }
        ));
        jScrollPane2.setViewportView(coursesTable);

        StudentPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 340, 390));

        courseStudentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        courseStudentLabel.setForeground(new java.awt.Color(255, 255, 255));
        courseStudentLabel.setText("Courses Of Students");
        StudentPanel.add(courseStudentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 150, 20));

        StudentsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StudentsLabel.setForeground(new java.awt.Color(255, 255, 255));
        StudentsLabel.setText("Students");
        StudentPanel.add(StudentsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 20));

        exitLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel1.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel1.setText("X");
        exitLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel1MouseClicked(evt);
            }
        });
        StudentPanel.add(exitLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 29));

        getContentPane().add(StudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 830, 530));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(242, 242, 242));
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 100, 280, 200));

        ServicePanel.setBackground(new java.awt.Color(0, 0, 0));
        ServicePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        ServicePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NoticeLink.setBackground(new java.awt.Color(0, 0, 0));
        NoticeLink.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        NoticeLink.setForeground(new java.awt.Color(255, 255, 255));
        NoticeLink.setText("Notice Management");
        NoticeLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoticeLinkMouseClicked(evt);
            }
        });
        ServicePanel.add(NoticeLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 160, 20));

        ServiceLabel.setBackground(new java.awt.Color(0, 0, 0));
        ServiceLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ServiceLabel.setForeground(new java.awt.Color(255, 255, 255));
        ServiceLabel.setText("Service");
        ServicePanel.add(ServiceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));
        ServicePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 21, -1, -1));

        studentLink.setBackground(new java.awt.Color(0, 0, 0));
        studentLink.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        studentLink.setForeground(new java.awt.Color(255, 255, 255));
        studentLink.setText("Student Management");
        studentLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLinkMouseClicked(evt);
            }
        });
        ServicePanel.add(studentLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 20));

        TeacherLink.setBackground(new java.awt.Color(0, 0, 0));
        TeacherLink.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        TeacherLink.setForeground(new java.awt.Color(255, 255, 255));
        TeacherLink.setText("Teacher Management");
        TeacherLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeacherLinkMouseClicked(evt);
            }
        });
        ServicePanel.add(TeacherLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 20));

        CourseLink.setBackground(new java.awt.Color(0, 0, 0));
        CourseLink.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        CourseLink.setForeground(new java.awt.Color(255, 255, 255));
        CourseLink.setText("Course Management");
        CourseLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseLinkMouseClicked(evt);
            }
        });
        ServicePanel.add(CourseLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 20));

        logoutLabel.setBackground(new java.awt.Color(0, 0, 0));
        logoutLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/001-logoute.png"))); // NOI18N
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });
        ServicePanel.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 90, 40));

        getContentPane().add(ServicePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 530));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1110, 670));

        setSize(new java.awt.Dimension(1113, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void studentLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLinkMouseClicked
        StudentPanel.setVisible(true);
        TeacherPanel.setVisible(false);
        CoursePanel.setVisible(false);
        NoticePanel.setVisible(false);
    }//GEN-LAST:event_studentLinkMouseClicked

    private void TeacherLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeacherLinkMouseClicked
        TeacherPanel.setVisible(true);
        CoursePanel.setVisible(false);
        NoticePanel.setVisible(false);
    }//GEN-LAST:event_TeacherLinkMouseClicked

    private void CourseLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseLinkMouseClicked
        CoursePanel.setVisible(true);
        NoticePanel.setVisible(false);
    }//GEN-LAST:event_CourseLinkMouseClicked

    private void NoticeLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoticeLinkMouseClicked
        NoticePanel.setVisible(true);
    }//GEN-LAST:event_NoticeLinkMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel1MouseClicked

    private void exitLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel2MouseClicked

    private void exitLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel3MouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        new LoginForm();
    }//GEN-LAST:event_logoutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CloursesTable;
    private javax.swing.JLabel CourseLabel;
    private javax.swing.JLabel CourseLink;
    private javax.swing.JPanel CoursePanel;
    private javax.swing.JLabel CoursesLabel;
    private javax.swing.JTable CoursesTable;
    private javax.swing.JTable CoursesTable1;
    private javax.swing.JTable CoursesTable2;
    private javax.swing.JLabel CoursesTeacherLabel;
    private javax.swing.JLabel CoursesTeacherLabel2;
    private javax.swing.JLabel NoticeLabel;
    private javax.swing.JLabel NoticeLink;
    private javax.swing.JPanel NoticePanel;
    private javax.swing.JLabel NoticesLabel;
    private javax.swing.JTable NoticesTable;
    private javax.swing.JLabel ServiceLabel;
    private javax.swing.JPanel ServicePanel;
    private javax.swing.JLabel StudentLabel;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JLabel StudentsLabel;
    private javax.swing.JLabel TeacherLabel;
    private javax.swing.JLabel TeacherLink;
    private javax.swing.JPanel TeacherPanel;
    private javax.swing.JLabel TeachersLabel;
    private javax.swing.JTable TeachersTable;
    private javax.swing.JLabel assignCourseLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel courseStudentLabel;
    private javax.swing.JTable coursesTable;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel exitLabel1;
    private javax.swing.JLabel exitLabel2;
    private javax.swing.JLabel exitLabel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel studentLink;
    private javax.swing.JTable studentsTable;
    // End of variables declaration//GEN-END:variables
}
