/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Frame;

import com.mycompany.coursemanagement.FileManagement;
import com.mycompany.coursemanagement.Admin;
import com.mycompany.coursemanagement.Student;
import com.mycompany.coursemanagement.Teacher;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ME1
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LoginForm() {
        initComponents();
        this.setVisible(true);
        txtemail.setBackground(new java.awt.Color(0,0,0,1));
        txtpassword.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        loginPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        subLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lineEmailLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        linePasswordLabel = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        questionLabel = new javax.swing.JLabel();
        goToRegisterPageButton = new javax.swing.JButton();
        studentRadioButton = new javax.swing.JRadioButton();
        chooseLabel = new javax.swing.JLabel();
        adminRadioButton = new javax.swing.JRadioButton();
        teacherRadioButton = new javax.swing.JRadioButton();
        sorryLabel = new javax.swing.JLabel();
        invalidEmailLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(0, 0, 0));
        loginPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        loginPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 29));

        loginLabel.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");
        loginPanel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 420, 41));

        subLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        subLabel.setForeground(new java.awt.Color(153, 153, 153));
        subLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subLabel.setText("Hello! Let's get started");
        loginPanel.add(subLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 420, -1));

        emailLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(242, 242, 242));
        emailLabel.setText("Email");
        loginPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 341, -1));

        txtemail.setBackground(new java.awt.Color(0, 0, 0));
        txtemail.setFont(txtemail.getFont().deriveFont(txtemail.getFont().getSize()+2f));
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.setBorder(null);
        loginPanel.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 240, 30));

        lineEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        lineEmailLabel.setText("_________________________________________");
        loginPanel.add(lineEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 290, 39));

        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        loginPanel.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 40, 39));

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        loginPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 341, -1));

        txtpassword.setBackground(new java.awt.Color(0, 0, 0));
        txtpassword.setFont(txtpassword.getFont().deriveFont(txtpassword.getFont().getSize()+2f));
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(null);
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        loginPanel.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 30));

        linePasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        linePasswordLabel.setText("_________________________________________");
        loginPanel.add(linePasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 290, 40));

        disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ineye.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        loginPanel.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 60, 30));

        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        loginPanel.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 40, 30));

        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 341, 40));

        questionLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(153, 153, 153));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionLabel.setText("Don't have an account?");
        loginPanel.add(questionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 210, 30));

        goToRegisterPageButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        goToRegisterPageButton.setForeground(new java.awt.Color(255, 255, 255));
        goToRegisterPageButton.setText("Register");
        goToRegisterPageButton.setContentAreaFilled(false);
        goToRegisterPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToRegisterPageButtonActionPerformed(evt);
            }
        });
        loginPanel.add(goToRegisterPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 90, 30));

        studentRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(studentRadioButton);
        studentRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        studentRadioButton.setText("Student");
        loginPanel.add(studentRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        chooseLabel.setBackground(new java.awt.Color(0, 0, 0));
        chooseLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chooseLabel.setForeground(new java.awt.Color(153, 153, 153));
        chooseLabel.setText("Choose your type !");
        loginPanel.add(chooseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 220, 20));

        adminRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(adminRadioButton);
        adminRadioButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        adminRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        adminRadioButton.setText("Admin");
        loginPanel.add(adminRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        teacherRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(teacherRadioButton);
        teacherRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        teacherRadioButton.setText("Teacher");
        loginPanel.add(teacherRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        sorryLabel.setBackground(new java.awt.Color(0, 0, 0));
        sorryLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sorryLabel.setForeground(new java.awt.Color(0, 153, 153));
        sorryLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginPanel.add(sorryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 480, 40));

        invalidEmailLabel.setForeground(new java.awt.Color(255, 0, 0));
        loginPanel.add(invalidEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 140, -1));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 620, 500));

        backgroundLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 680));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(242, 242, 242));
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 100, 280, 200));

        setSize(new java.awt.Dimension(1198, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
         System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        txtpassword.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        txtpassword.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void goToRegisterPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToRegisterPageButtonActionPerformed
        RegisterForm r = new RegisterForm();
        r.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_goToRegisterPageButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        if((txtemail.getText().isBlank()|| txtpassword.getText().isBlank())||!((adminRadioButton.isSelected())||(studentRadioButton.isSelected())||(teacherRadioButton.isSelected()))){       
            //UIManager.put("OptionPane.background", Color.BLACK);
            //UIManager.put("Panels.background", Color.BLACK);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            JLabel messageLabel = new JLabel("Please enter all fields");
            messageLabel.setOpaque(true);
            //messageLabel.setBackground(Color.BLACK);
            messageLabel.setForeground(Color.BLACK);
            JOptionPane.showMessageDialog(this, messageLabel, "Error!!", JOptionPane.ERROR_MESSAGE);
            txtemail.setText("");
            txtpassword.setText("");
            buttonGroup1.clearSelection();
        }else if(!FileManagement.validEmail(txtemail.getText())){
            invalidEmailLabel.setForeground(Color.RED);
            invalidEmailLabel.setText("invalid Email !!");
        }else{
            if(adminRadioButton.isSelected()){
                Admin admin = new Admin();
                if(admin.logIn(txtemail.getText(), txtpassword.getText())){
                    //AdminForm af = new AdminForm();
                    //af.setVisible(true);
                    this.dispose();
                }
                else{
                    sorryLabel.setText("Sorry, you don't have an account ... Please, create an account and login again");
                } 
            }
            else if(teacherRadioButton.isSelected()){
                Teacher teacher = new Teacher();
                if(teacher.logIn(txtemail.getText(), txtpassword.getText())){
                    //TeacherForm tf = new TeacherForm();
                    //tf.setVisible(true);
                    this.dispose();
                }
                else{
                    sorryLabel.setText("Sorry, you don't have an account ... Please, create an account and login again");
                } 
            }
            else if(studentRadioButton.isSelected()){
                Student student = new Student();
                if(student.logIn(txtemail.getText(), txtpassword.getText())){
                    //StudentForm sf = new StudentForm();
                    //sf.setVisible(true);
                    this.dispose();
                }
                else{
                    sorryLabel.setText("Sorry, you don't have an account ... Please, create an account and login again");
                } 
            }
        }
        invalidEmailLabel.setText("");
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminRadioButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel chooseLabel;
    private javax.swing.JLabel disable;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JButton goToRegisterPageButton;
    private javax.swing.JLabel invalidEmailLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel lineEmailLabel;
    private javax.swing.JLabel linePasswordLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel show;
    private javax.swing.JLabel sorryLabel;
    private javax.swing.JRadioButton studentRadioButton;
    private javax.swing.JLabel subLabel;
    private javax.swing.JRadioButton teacherRadioButton;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
