/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Frame;

import com.mycompany.coursemanagement.Admin;
import com.mycompany.coursemanagement.FileManagement;
import com.mycompany.coursemanagement.Student;
import com.mycompany.coursemanagement.Teacher;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ME1
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public RegisterForm() {
        initComponents();
        txtusername.setBackground(new java.awt.Color(0,0,0,1));
        txtemail.setBackground(new java.awt.Color(0,0,0,1));
        txtpassword.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        registerPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        subLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        lineUserNameLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        linepasswordLabel = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        questionLabel = new javax.swing.JLabel();
        goToLoginPageButton = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        emailimgLabel = new javax.swing.JLabel();
        lineEmailLabel = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        ifRegisterGoToLoginLabel = new javax.swing.JLabel();
        invalidEmailLabel = new javax.swing.JLabel();
        adminRadioButton = new javax.swing.JRadioButton();
        teacherRadioButton = new javax.swing.JRadioButton();
        studentRadioButton = new javax.swing.JRadioButton();
        chooseLabel = new javax.swing.JLabel();
        teacherLabel = new javax.swing.JLabel();
        txtspecialty = new javax.swing.JTextField();
        linepasswordLabel1 = new javax.swing.JLabel();
        lineteacherLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPanel.setBackground(new java.awt.Color(0, 0, 0));
        registerPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        registerPanel.setForeground(new java.awt.Color(0, 153, 255));
        registerPanel.setToolTipText("");
        registerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registerPanel.setDoubleBuffered(false);
        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        registerPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 40, 29));

        registerLabel.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Register");
        registerPanel.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 420, 41));

        subLabel.setBackground(new java.awt.Color(0, 0, 0));
        subLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        subLabel.setForeground(new java.awt.Color(153, 153, 153));
        subLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subLabel.setText("And, Start journey with us");
        registerPanel.add(subLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 420, -1));

        usernameLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(242, 242, 242));
        usernameLabel.setText("Username");
        registerPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, -1));

        lineUserNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lineUserNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lineUserNameLabel.setText("_________________________________________");
        lineUserNameLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        registerPanel.add(lineUserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 280, 20));

        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        registerPanel.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 40, 39));

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(242, 242, 242));
        passwordLabel.setText("Password");
        registerPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 70, 20));

        txtpassword.setBackground(new java.awt.Color(0, 0, 0));
        txtpassword.setFont(txtpassword.getFont().deriveFont(txtpassword.getFont().getSize()+2f));
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(null);
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        registerPanel.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 240, 30));

        linepasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        linepasswordLabel.setText("_________________________________________");
        linepasswordLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        registerPanel.add(linepasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, 20));

        disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ineye.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        registerPanel.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 40, 40));

        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        registerPanel.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 40, 40));

        registerButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerButton.setText("REGISTER");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        registerPanel.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 350, 40));

        questionLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(153, 153, 153));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionLabel.setText("Do you have an account?");
        registerPanel.add(questionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 213, 30));

        goToLoginPageButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        goToLoginPageButton.setForeground(new java.awt.Color(255, 255, 255));
        goToLoginPageButton.setText("Login");
        goToLoginPageButton.setContentAreaFilled(false);
        goToLoginPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLoginPageButtonActionPerformed(evt);
            }
        });
        registerPanel.add(goToLoginPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 80, 30));

        txtusername.setBackground(new java.awt.Color(0, 0, 0));
        txtusername.setFont(txtusername.getFont().deriveFont(txtusername.getFont().getSize()+2f));
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setBorder(null);
        registerPanel.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 240, 30));

        emailimgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailimgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/email.png"))); // NOI18N
        registerPanel.add(emailimgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 40, 39));

        lineEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        lineEmailLabel.setText("_________________________________________");
        lineEmailLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        registerPanel.add(lineEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 290, 20));

        txtemail.setBackground(new java.awt.Color(0, 0, 0));
        txtemail.setFont(txtemail.getFont().deriveFont(txtemail.getFont().getSize()+2f));
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.setBorder(null);
        registerPanel.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 240, 30));

        emailLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(242, 242, 242));
        emailLabel.setText("Email");
        registerPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 70, -1));

        ifRegisterGoToLoginLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ifRegisterGoToLoginLabel.setForeground(new java.awt.Color(0, 153, 153));
        registerPanel.add(ifRegisterGoToLoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 440, 30));

        invalidEmailLabel.setBackground(new java.awt.Color(0, 0, 0));
        invalidEmailLabel.setForeground(new java.awt.Color(255, 0, 0));
        registerPanel.add(invalidEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 210, -1));

        adminRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(adminRadioButton);
        adminRadioButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        adminRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        adminRadioButton.setText("Admin");
        registerPanel.add(adminRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));

        teacherRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(teacherRadioButton);
        teacherRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        teacherRadioButton.setText("Teacher");
        registerPanel.add(teacherRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, 30));

        studentRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(studentRadioButton);
        studentRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        studentRadioButton.setText("Student");
        registerPanel.add(studentRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, 30));

        chooseLabel.setBackground(new java.awt.Color(0, 0, 0));
        chooseLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chooseLabel.setForeground(new java.awt.Color(153, 153, 153));
        chooseLabel.setText("Choose your type !");
        registerPanel.add(chooseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 220, 30));

        teacherLabel.setBackground(new java.awt.Color(0, 0, 0));
        teacherLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherLabel.setForeground(new java.awt.Color(255, 255, 255));
        teacherLabel.setText("- If you are a Teacher, Enter your specialty");
        registerPanel.add(teacherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 270, 30));

        txtspecialty.setBackground(new java.awt.Color(0, 0, 0));
        registerPanel.add(txtspecialty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 210, -1));

        linepasswordLabel1.setForeground(new java.awt.Color(255, 255, 255));
        linepasswordLabel1.setText("_________________________________________");
        linepasswordLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        registerPanel.add(linepasswordLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, 20));

        lineteacherLabel.setBackground(new java.awt.Color(0, 0, 0));
        lineteacherLabel.setForeground(new java.awt.Color(255, 255, 255));
        lineteacherLabel.setText("_____________________________________");
        registerPanel.add(lineteacherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 230, 20));

        getContentPane().add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, 550));

        backgroundLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1200, 680));

        setSize(new java.awt.Dimension(1169, 684));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        txtpassword.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void goToLoginPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLoginPageButtonActionPerformed
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_goToLoginPageButtonActionPerformed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        txtpassword.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        if(teacherRadioButton.isSelected()){
            if((txtusername.getText().isBlank()||txtemail.getText().isBlank()|| txtpassword.getText().isBlank())||txtspecialty.getText().isBlank()){     
                UIManager.put("OptionPane.background", Color.BLACK);
                UIManager.put("Panels.background", Color.BLACK);
                UIManager.put("OptionPane.messageForeground", Color.WHITE);
                JLabel messageLabel = new JLabel("Please enter all fields");
                messageLabel.setOpaque(true);
                messageLabel.setBackground(Color.BLACK);
                messageLabel.setForeground(Color.WHITE);
                JOptionPane.showMessageDialog(this, messageLabel, "Error!!", JOptionPane.ERROR_MESSAGE);
                invalidEmailLabel.setText("");
                txtusername.setText("");
                txtemail.setText("");
                txtpassword.setText("");
                buttonGroup1.clearSelection();
            }else if(!FileManagement.validEmail(txtemail.getText())){
                invalidEmailLabel.setForeground(Color.RED);
                invalidEmailLabel.setText("invalid Email !!");
            }else{
                Teacher teacher1 = new Teacher(txtusername.getText(), txtemail.getText(), txtpassword.getText(),txtspecialty.getText(), true);
                if(FileManagement.emailExists(txtemail.getText(), "teachers.txt")){
                    invalidEmailLabel.setForeground(Color.getHSBColor(0, 153, 153));
                    invalidEmailLabel.setText("This Email is already in use");
                }else{
                    try {
                        FileManagement.writeSingleObjectToFile(teacher1, "teachers.txt", teacher -> teacher.objectToString());
                        ifRegisterGoToLoginLabel.setText("The account has been created, Please go to the login page ...");
                    } catch (IOException ex) {
                        Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }else{
            if((txtusername.getText().isBlank()||txtemail.getText().isBlank()|| txtpassword.getText().isBlank())||!((adminRadioButton.isSelected())||(studentRadioButton.isSelected()))){     
                UIManager.put("OptionPane.background", Color.BLACK);
                UIManager.put("Panels.background", Color.BLACK);
                UIManager.put("OptionPane.messageForeground", Color.WHITE);
                JLabel messageLabel = new JLabel("Please enter all fields");
                messageLabel.setOpaque(true);
                messageLabel.setBackground(Color.BLACK);
                messageLabel.setForeground(Color.WHITE);
                JOptionPane.showMessageDialog(this, messageLabel, "Error!!", JOptionPane.ERROR_MESSAGE);
                invalidEmailLabel.setText("");
                txtusername.setText("");
                txtemail.setText("");
                txtpassword.setText("");
                buttonGroup1.clearSelection();
            }else if(!FileManagement.validEmail(txtemail.getText())){
                invalidEmailLabel.setForeground(Color.RED);
                invalidEmailLabel.setText("invalid Email !!");
            }else{
                if(adminRadioButton.isSelected()){
                    Admin admin1 = new Admin(txtusername.getText(), txtemail.getText(), txtpassword.getText(), true);
                    if(FileManagement.emailExists(txtemail.getText(), "admins.txt")){
                        invalidEmailLabel.setForeground(Color.getHSBColor(0, 153, 153));
                        invalidEmailLabel.setText("This Email is already in use");

                    }else{
                        try {
                            FileManagement.writeSingleObjectToFile(admin1, "admins.txt", admin -> admin.objectToString());
                            ifRegisterGoToLoginLabel.setText("The account has been created, Please go to the login page ...");
                        } catch (IOException ex) {
                            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }else if(studentRadioButton.isSelected()){
                    Student student1 = new Student(txtusername.getText(), txtemail.getText(), txtpassword.getText(), true);
                    if(FileManagement.emailExists(txtemail.getText(), "students.txt")){
                        invalidEmailLabel.setForeground(Color.getHSBColor(0, 153, 153));
                        invalidEmailLabel.setText("This Email is already in use");

                    }else{
                        try {
                            FileManagement.writeSingleObjectToFile(student1, "students.txt", student -> student.objectToString());
                            ifRegisterGoToLoginLabel.setText("The account has been created, Please go to the login page ...");
                        } catch (IOException ex) {
                            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminRadioButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel chooseLabel;
    private javax.swing.JLabel disable;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailimgLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JButton goToLoginPageButton;
    private javax.swing.JLabel ifRegisterGoToLoginLabel;
    private javax.swing.JLabel invalidEmailLabel;
    private javax.swing.JLabel lineEmailLabel;
    private javax.swing.JLabel lineUserNameLabel;
    private javax.swing.JLabel linepasswordLabel;
    private javax.swing.JLabel linepasswordLabel1;
    private javax.swing.JLabel lineteacherLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel show;
    private javax.swing.JRadioButton studentRadioButton;
    private javax.swing.JLabel subLabel;
    private javax.swing.JLabel teacherLabel;
    private javax.swing.JRadioButton teacherRadioButton;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtspecialty;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
