/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Frame;

/**
 *
 * @author shahd
 */
public class StudentForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DetailsPanel = new javax.swing.JPanel();
        EnrollPanel = new javax.swing.JPanel();
        StudentTitle = new javax.swing.JLabel();
        describtion = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        Enroll = new javax.swing.JButton();
        exitLabel = new javax.swing.JLabel();
        Enroll1 = new javax.swing.JButton();
        DetailsButton = new javax.swing.JButton();
        enrollCourseLabel = new javax.swing.JLabel();
        viewAvailableLabel = new javax.swing.JLabel();
        StudentTitle1 = new javax.swing.JLabel();
        exitLabel1 = new javax.swing.JLabel();
        logoutLabel1 = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();
        txtCourseGrade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ButtonCourseGrade = new javax.swing.JButton();
        submitAssignment = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        EnrollButton = new javax.swing.JButton();
        describtion2 = new javax.swing.JLabel();
        DetailsStPanel = new javax.swing.JPanel();
        AvailableCoursesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CoursesTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        DetailsTable = new javax.swing.JTable();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DetailsPanel.setBackground(new java.awt.Color(0, 0, 0));
        DetailsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        DetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EnrollPanel.setBackground(new java.awt.Color(0, 0, 0));
        EnrollPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        EnrollPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentTitle.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        StudentTitle.setForeground(new java.awt.Color(255, 255, 255));
        StudentTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/group.png"))); // NOI18N
        StudentTitle.setText("Student");
        EnrollPanel.add(StudentTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 420, 41));

        describtion.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        describtion.setForeground(new java.awt.Color(255, 255, 255));
        describtion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        describtion.setText("Hello! Let's learn");
        EnrollPanel.add(describtion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 420, -1));

        logoutLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/001-logoute.png"))); // NOI18N
        logoutLabel.setText("Logout");
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });
        EnrollPanel.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 80, 20));

        Enroll.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Enroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/homework.png"))); // NOI18N
        Enroll.setText("View");
        Enroll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enroll.setMaximumSize(new java.awt.Dimension(119, 43));
        Enroll.setMinimumSize(new java.awt.Dimension(119, 43));
        EnrollPanel.add(Enroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 160, 50));

        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        EnrollPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 29));

        Enroll1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Enroll1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/checklist.png"))); // NOI18N
        Enroll1.setText("Enroll");
        Enroll1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enroll1.setMaximumSize(new java.awt.Dimension(119, 43));
        Enroll1.setMinimumSize(new java.awt.Dimension(119, 43));
        Enroll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enroll1ActionPerformed(evt);
            }
        });
        EnrollPanel.add(Enroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 160, 50));

        DetailsButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DetailsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/skills.png"))); // NOI18N
        DetailsButton.setText("Details About You");
        DetailsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DetailsButton.setMaximumSize(new java.awt.Dimension(119, 43));
        DetailsButton.setMinimumSize(new java.awt.Dimension(119, 43));
        DetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsButtonActionPerformed(evt);
            }
        });
        EnrollPanel.add(DetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 300, 50));

        enrollCourseLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        enrollCourseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enrollCourseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enrollCourseLabel.setText("Enroll Course");
        EnrollPanel.add(enrollCourseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, -1));

        viewAvailableLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        viewAvailableLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewAvailableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewAvailableLabel.setText("View Available Courses");
        EnrollPanel.add(viewAvailableLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 300, -1));

        DetailsPanel.add(EnrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        StudentTitle1.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        StudentTitle1.setForeground(new java.awt.Color(255, 255, 255));
        StudentTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentTitle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/group.png"))); // NOI18N
        StudentTitle1.setText("Student");
        DetailsPanel.add(StudentTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 420, 41));

        exitLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel1.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel1.setText("X");
        exitLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel1MouseClicked(evt);
            }
        });
        DetailsPanel.add(exitLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 29));

        logoutLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        logoutLabel1.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/001-logoute.png"))); // NOI18N
        logoutLabel1.setText("Logout");
        logoutLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabel1MouseClicked(evt);
            }
        });
        DetailsPanel.add(logoutLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 80, 20));

        courseLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        courseLabel.setForeground(new java.awt.Color(242, 242, 242));
        courseLabel.setText("Course");
        DetailsPanel.add(courseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 341, -1));

        txtCourseGrade.setBackground(new java.awt.Color(0, 0, 0));
        txtCourseGrade.setFont(txtCourseGrade.getFont().deriveFont(txtCourseGrade.getFont().getSize()+2f));
        txtCourseGrade.setForeground(new java.awt.Color(255, 255, 255));
        txtCourseGrade.setBorder(null);
        txtCourseGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseGradeActionPerformed(evt);
            }
        });
        DetailsPanel.add(txtCourseGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("__________________________________");
        DetailsPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 300, 39));

        ButtonCourseGrade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonCourseGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/scholarship.png"))); // NOI18N
        ButtonCourseGrade.setText("Grade");
        ButtonCourseGrade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCourseGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCourseGradeActionPerformed(evt);
            }
        });
        DetailsPanel.add(ButtonCourseGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 190, 50));

        submitAssignment.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        submitAssignment.setForeground(new java.awt.Color(255, 255, 255));
        submitAssignment.setText("Submit Assignment");
        DetailsPanel.add(submitAssignment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        Submit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/submit.png"))); // NOI18N
        Submit.setText("Submit");
        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.setMaximumSize(new java.awt.Dimension(119, 43));
        Submit.setMinimumSize(new java.awt.Dimension(119, 43));
        DetailsPanel.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 190, 50));

        EnrollButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EnrollButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/skills.png"))); // NOI18N
        EnrollButton.setText("Enroll New Courses");
        EnrollButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EnrollButton.setMaximumSize(new java.awt.Dimension(119, 43));
        EnrollButton.setMinimumSize(new java.awt.Dimension(119, 43));
        EnrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollButtonActionPerformed(evt);
            }
        });
        DetailsPanel.add(EnrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 300, 50));

        describtion2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        describtion2.setForeground(new java.awt.Color(255, 255, 255));
        describtion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        describtion2.setText("Hello! Let's learn");
        DetailsPanel.add(describtion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 420, -1));

        getContentPane().add(DetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 650, 500));

        DetailsStPanel.setBackground(new java.awt.Color(0, 0, 0));
        DetailsStPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AvailableCoursesPanel.setBackground(new java.awt.Color(0, 0, 0));
        AvailableCoursesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoursesTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Courses", "Prices"
            }
        ));
        jScrollPane1.setViewportView(CoursesTable);

        AvailableCoursesPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 460, 430));

        DetailsStPanel.add(AvailableCoursesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 420));

        DetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Email", "Courses", "CoGrade", "AssGrade"
            }
        ));
        jScrollPane6.setViewportView(DetailsTable);

        DetailsStPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 460, 420));

        getContentPane().add(DetailsStPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 440, 420));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel1MouseClicked

    private void logoutLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabel1MouseClicked
        new LoginForm();
    }//GEN-LAST:event_logoutLabel1MouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        new LoginForm();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void Enroll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enroll1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Enroll1ActionPerformed

    private void DetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsButtonActionPerformed
        EnrollPanel.setVisible(false);
        DetailsPanel.setVisible(true);
        AvailableCoursesPanel.setVisible(false);
        DetailsStPanel.setVisible(true);

    }//GEN-LAST:event_DetailsButtonActionPerformed

    private void txtCourseGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseGradeActionPerformed

    private void ButtonCourseGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCourseGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCourseGradeActionPerformed

    private void EnrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollButtonActionPerformed
        EnrollPanel.setVisible(true);
        AvailableCoursesPanel.setVisible(true);

    }//GEN-LAST:event_EnrollButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AvailableCoursesPanel;
    private javax.swing.JButton ButtonCourseGrade;
    private javax.swing.JTable CoursesTable;
    private javax.swing.JButton DetailsButton;
    private javax.swing.JPanel DetailsPanel;
    private javax.swing.JPanel DetailsStPanel;
    private javax.swing.JTable DetailsTable;
    private javax.swing.JButton Enroll;
    private javax.swing.JButton Enroll1;
    private javax.swing.JButton EnrollButton;
    private javax.swing.JPanel EnrollPanel;
    private javax.swing.JLabel StudentTitle;
    private javax.swing.JLabel StudentTitle1;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JLabel describtion;
    private javax.swing.JLabel describtion2;
    private javax.swing.JLabel enrollCourseLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel exitLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel logoutLabel1;
    private javax.swing.JLabel submitAssignment;
    private javax.swing.JTextField txtCourseGrade;
    private javax.swing.JLabel viewAvailableLabel;
    // End of variables declaration//GEN-END:variables
}
