/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Frame;

/**
 *
 * @author ME1
 */
public class TeacherDashboard extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public TeacherDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        StudentPanel = new javax.swing.JPanel();
        StudentLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        exitLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ServicePanel = new javax.swing.JPanel();
        NoticeLink = new javax.swing.JLabel();
        ServiceLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentLink = new javax.swing.JLabel();
        TeacherLink = new javax.swing.JLabel();
        CourseLink = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        NoticePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        exitLabel2 = new javax.swing.JLabel();
        NoticeLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CoursePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CourseLabel = new javax.swing.JLabel();
        exitLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        TeacherPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TeacherLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        NoticePanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        exitLabel4 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        tfName1 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
        tfEmail1 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel18 = new javax.swing.JLabel();
        tfPhone1 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel19 = new javax.swing.JLabel();
        tfAddress1 = new javax.swing.JTextField();
        javax.swing.JButton btnAdd1 = new javax.swing.JButton();
        javax.swing.JButton btnClear1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        NoticeLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentPanel.setBackground(new java.awt.Color(0, 0, 0));
        StudentPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        StudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentLabel.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        StudentLabel.setForeground(new java.awt.Color(255, 255, 255));
        StudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StudentLabel.setText("Your Courses");
        StudentPanel.add(StudentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 420, 41));

        coursesTable.setBackground(new java.awt.Color(0, 0, 0));
        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Course Name", "Description", "Time Period"
            }
        ));
        jScrollPane2.setViewportView(coursesTable);

        StudentPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 810, 390));

        exitLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel1.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel1.setText("X");
        exitLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel1MouseClicked(evt);
            }
        });
        StudentPanel.add(exitLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 29));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background.jpg"))); // NOI18N
        StudentPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        getContentPane().add(StudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 830, 530));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(242, 242, 242));
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 100, 280, 200));

        ServicePanel.setBackground(new java.awt.Color(0, 0, 0));
        ServicePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        ServicePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NoticeLink.setBackground(new java.awt.Color(0, 0, 0));
        NoticeLink.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        NoticeLink.setForeground(new java.awt.Color(255, 255, 255));
        NoticeLink.setText("Add Assignments");
        NoticeLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoticeLinkMouseClicked(evt);
            }
        });
        ServicePanel.add(NoticeLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 20));

        ServiceLabel.setBackground(new java.awt.Color(0, 0, 0));
        ServiceLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ServiceLabel.setForeground(new java.awt.Color(255, 255, 255));
        ServiceLabel.setText("Service");
        ServicePanel.add(ServiceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));
        ServicePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 21, -1, -1));

        studentLink.setBackground(new java.awt.Color(0, 0, 0));
        studentLink.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        studentLink.setForeground(new java.awt.Color(255, 255, 255));
        studentLink.setText("Your Courses ");
        studentLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLinkMouseClicked(evt);
            }
        });
        ServicePanel.add(studentLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 20));

        TeacherLink.setBackground(new java.awt.Color(0, 0, 0));
        TeacherLink.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        TeacherLink.setForeground(new java.awt.Color(255, 255, 255));
        TeacherLink.setText("Your Students");
        TeacherLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeacherLinkMouseClicked(evt);
            }
        });
        ServicePanel.add(TeacherLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 20));

        CourseLink.setBackground(new java.awt.Color(0, 0, 0));
        CourseLink.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        CourseLink.setForeground(new java.awt.Color(255, 255, 255));
        CourseLink.setText("Assign Grades to Students ");
        CourseLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseLinkMouseClicked(evt);
            }
        });
        ServicePanel.add(CourseLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 20));

        logoutLabel.setBackground(new java.awt.Color(0, 0, 0));
        logoutLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/001-logoute.png"))); // NOI18N
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });
        ServicePanel.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 90, 40));

        getContentPane().add(ServicePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 530));

        NoticePanel.setBackground(new java.awt.Color(0, 0, 0));
        NoticePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        NoticePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        NoticePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        exitLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel2.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel2.setText("X");
        exitLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel2MouseClicked(evt);
            }
        });
        NoticePanel.add(exitLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 29));

        NoticeLabel.setBackground(new java.awt.Color(0, 0, 0));
        NoticeLabel.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        NoticeLabel.setForeground(new java.awt.Color(255, 255, 255));
        NoticeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoticeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/teacher.png"))); // NOI18N
        NoticeLabel.setText("Teacher Dashboard");
        NoticePanel.add(NoticeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teacher Speciality : ");
        NoticePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Computer Science");
        NoticePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 140, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Teacher Name : ");
        NoticePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Soliman Waleed ");
        NoticePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 140, 30));

        getContentPane().add(NoticePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(3050, 560, 830, 530));

        CoursePanel.setBackground(new java.awt.Color(0, 0, 0));
        CoursePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        CoursePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CoursePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        CourseLabel.setBackground(new java.awt.Color(0, 0, 0));
        CourseLabel.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        CourseLabel.setForeground(new java.awt.Color(255, 255, 255));
        CourseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CourseLabel.setText("Assign Grades to Students ");
        CoursePanel.add(CourseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        exitLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel3.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel3.setText("X");
        exitLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel3MouseClicked(evt);
            }
        });
        CoursePanel.add(exitLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 29));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Assignment Name : ");
        CoursePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assignment1", "Assignment 2", "Assignment3" }));
        CoursePanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student Name : ");
        CoursePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student1", "Student 2", "Student3" }));
        CoursePanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Assign");
        CoursePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 250, -1));

        getContentPane().add(CoursePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 40, 830, 530));

        TeacherPanel.setBackground(new java.awt.Color(0, 0, 0));
        TeacherPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        TeacherPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TeacherPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        TeacherLabel.setBackground(new java.awt.Color(0, 0, 0));
        TeacherLabel.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        TeacherLabel.setForeground(new java.awt.Color(255, 255, 255));
        TeacherLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TeacherLabel.setText("Your Students");
        TeacherPanel.add(TeacherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 330, -1));

        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        TeacherPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 29));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        studentsTable.setBackground(new java.awt.Color(0, 0, 0));
        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email"
            }
        ));
        jScrollPane1.setViewportView(studentsTable);

        TeacherPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 810, 390));

        getContentPane().add(TeacherPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, 830, 530));

        NoticePanel1.setBackground(new java.awt.Color(0, 0, 0));
        NoticePanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        NoticePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        NoticePanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        exitLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitLabel4.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel4.setText("X");
        exitLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel4MouseClicked(evt);
            }
        });
        NoticePanel1.add(exitLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 29));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setOpaque(false);

        tfName1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel17.setText("Email");

        tfEmail1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        tfEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmail1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel18.setText("Phone");

        tfPhone1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        tfPhone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhone1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel19.setText("Address");

        tfAddress1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        tfAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddress1ActionPerformed(evt);
            }
        });

        btnAdd1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnAdd1.setText("Add");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnClear1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnClear1.setText("Clear");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Course Name");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Assignment Title");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Assignment Description");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Assignment DeadLine");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfName1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tfPhone1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
            .addComponent(tfAddress1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnClear1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfEmail1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear1))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );

        NoticePanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 810, 350));

        NoticeLabel2.setBackground(new java.awt.Color(0, 0, 0));
        NoticeLabel2.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        NoticeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        NoticeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoticeLabel2.setText("Add Assignment");
        NoticePanel1.add(NoticeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        getContentPane().add(NoticePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2370, 20, 830, 530));

        setSize(new java.awt.Dimension(3948, 1383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void studentLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLinkMouseClicked
        StudentPanel.setVisible(true);
        TeacherPanel.setVisible(false);
        CoursePanel.setVisible(false);
        NoticePanel.setVisible(false);
    }//GEN-LAST:event_studentLinkMouseClicked

    private void TeacherLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeacherLinkMouseClicked
        TeacherPanel.setVisible(true);
        CoursePanel.setVisible(false);
        NoticePanel.setVisible(false);
    }//GEN-LAST:event_TeacherLinkMouseClicked

    private void CourseLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseLinkMouseClicked
        CoursePanel.setVisible(true);
        NoticePanel.setVisible(false);
    }//GEN-LAST:event_CourseLinkMouseClicked

    private void NoticeLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoticeLinkMouseClicked
        NoticePanel.setVisible(true);
    }//GEN-LAST:event_NoticeLinkMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel1MouseClicked

    private void exitLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel2MouseClicked

    private void exitLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel3MouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        new LoginForm();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void exitLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitLabel4MouseClicked

    private void tfEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmail1ActionPerformed

    private void tfPhone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhone1ActionPerformed

    private void tfAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddress1ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CourseLabel;
    private javax.swing.JLabel CourseLink;
    private javax.swing.JPanel CoursePanel;
    private javax.swing.JLabel NoticeLabel;
    private javax.swing.JLabel NoticeLabel2;
    private javax.swing.JLabel NoticeLink;
    private javax.swing.JPanel NoticePanel;
    private javax.swing.JPanel NoticePanel1;
    private javax.swing.JLabel ServiceLabel;
    private javax.swing.JPanel ServicePanel;
    private javax.swing.JLabel StudentLabel;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JLabel TeacherLabel;
    private javax.swing.JLabel TeacherLink;
    private javax.swing.JPanel TeacherPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable coursesTable;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel exitLabel1;
    private javax.swing.JLabel exitLabel2;
    private javax.swing.JLabel exitLabel3;
    private javax.swing.JLabel exitLabel4;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel studentLink;
    private javax.swing.JTable studentsTable;
    private javax.swing.JTextField tfAddress1;
    private javax.swing.JTextField tfEmail1;
    private javax.swing.JTextField tfName1;
    private javax.swing.JTextField tfPhone1;
    // End of variables declaration//GEN-END:variables
}
